<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXBdszM\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXBdszM/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSXBdszM.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSXBdszM\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSXBdszM\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'SXBdszM',
    'container.build_id' => 'de22b8bd',
    'container.build_time' => 1519245519,
));
